version: "3.8"

services:
  postgres:
    # image: postgres:12
    image: timescale/timescaledb-postgis:latest-pg12
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: brewpass-dev
      POSTGRES_DB: brewpass-dev
      POSTGRES_PASSWORD: brewpass-dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api-server:
    build:
      context: ./go
      dockerfile: Dockerfile.dev
    image: brewpass-go-dev:latest
    depends_on:
      - postgres
    expose:
      - "9000"
    working_dir: /app/go
    command: make dev
    environment:
      GOCACHE: /go/pkg/go-cache
      PG_URL: postgres://brewpass-dev:brewpass-dev@postgres:5432/brewpass-dev?sslmode=disable
    volumes:
      - .:/app
      - go_pkg:/go/pkg

  hasura:
    image: hasura/graphql-engine:v1.3.2.cli-migrations-v2
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always
    working_dir: /var/hasura
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://brewpass-dev:brewpass-dev@postgres:5432/brewpass-dev?sslmode=disable
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # access console using `hasura console` so that migrations are recorded
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_MIGRATIONS_DIR: /var/hasura/migrations
      HASURA_GRAPHQL_METADATA_DIR: /var/hasura/metadata
    volumes:
      - ./hasura:/var/hasura

  nginx:
    image: nginx:latest
    depends_on:
      - api-server
      - hasura
    ports:
      - "3000:3000"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf

volumes:
  postgres_data:
  go_pkg:
