// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

type User struct {
	ID     string       `json:"id"`
	Name   string       `json:"name"`
	Email  string       `json:"email"`
	Groups []*UserGroup `json:"groups"`
}

type UserGroup struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Slug  string  `json:"slug"`
	Users []*User `json:"users"`
}
